package level;

import utils.Pair;

public class Level9 extends Level {
    public Level9() {
        super(9, 80, 15, new Pair[]{
                new Pair<>(11, 2),
                new Pair<>(10, 10),
                new Pair<>(11, 11),
                new Pair<>(10, 11),
                new Pair<>(11, 10),
                new Pair<>(12, 11),
                new Pair<>(10, 2),
                new Pair<>(15, 10),
                new Pair<>(18, 11),
                new Pair<>(20, 21),
                new Pair<>(21, 18),
                new Pair<>(20, 20),
                new Pair<>(3, 22),
                new Pair<>(4, 10),
                new Pair<>(19, 11),
                new Pair<>(17, 21),
                new Pair<>(10, 20),
                new Pair<>(20, 10),
                new Pair<>(1, 18),
                new Pair<>(2, 11),
                new Pair<>(2, 20),
                new Pair<>(7, 7),
                new Pair<>(4, 4),
                new Pair<>(4, 22),
                new Pair<>(20, 1),
                new Pair<>(6, 11),
                new Pair<>(11, 6),
                new Pair<>(1, 3),
                new Pair<>(17, 13),
                new Pair<>(10, 13),
                new Pair<>(2, 3),
                new Pair<>(8, 22),
                new Pair<>(9, 22),
                new Pair<>(20, 3),
                new Pair<>(20, 2),
                new Pair<>(22, 22),
                new Pair<>(4, 14),
                new Pair<>(20, 14),
                new Pair<>(6, 15),
                new Pair<>(20, 19),
                new Pair<>(20, 15),
                new Pair<>(20, 16),
                new Pair<>(20, 17),
                new Pair<>(20, 18),
                new Pair<>(12, 12),
                new Pair<>(12, 13),
                new Pair<>(12, 14),
                new Pair<>(12, 15),
                new Pair<>(12, 16),
                new Pair<>(22, 12),
                new Pair<>(16, 4),
                new Pair<>(15, 3),
                new Pair<>(17, 5),
                new Pair<>(16, 20),
                new Pair<>(14, 21),
        });
    }
}
